### ISSUE TITLE
error in installing ember calendar

### ISSUE THREAD

**Issue by marendra** [alphasights/ember-calendar#28]
i just want to install ember calendar using : ember install ember-calendar , and i found error like this : 

/Users/marendra/workspace/testcal/node_modules/ember-calendar/blueprints/ember-calendar/index.js:10
    }).then(() => {
             ^
Unexpected token )
/Users/marendra/workspace/testcal/node_modules/ember-calendar/blueprints/ember-calendar/index.js:10
    }).then(() => {
             ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Function.Blueprint.load (/Users/marendra/workspace/testcal/node_modules/ember-cli/lib/models/blueprint.js:1401:25)
    at Function.Blueprint.lookup (/Users/marendra/workspace/testcal/node_modules/ember-cli/lib/models/blueprint.js:1376:24)
    at Class.module.exports.Task.extend.lookupBlueprint (/Users/marendra/workspace/testcal/node_modules/ember-cli/lib/tasks/generate-from-blueprint.js:91:22)

currently I'm using ember-cli 1.13.12

thanks

**Comment by Arkham** [comment]
Hey @marendra, that's a really weird error.. Which version of node and npm are you using?

**Comment by marendra** [comment]
Arifs-MBP:testcal marendra$ node -v
v0.12.7
Arifs-MBP:testcal marendra$ npm -version
2.11.3

**Comment by Arkham** [comment]
Could you try upgrading node to version 5.1.0 and repeating the process I've described here? https://github.com/alphasights/ember-calendar/issues/25#issuecomment-158943251

**Comment by marendra** [comment]
@Arkham hei man, thanks, problem solved after upgrading the node and the npm
